CREATE DATABASE IF NOT EXISTS burgersDB;
USE burgersDB;

DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers (
    id INT AUTO_INCREMENT NOT NULL,
    burger_name VARCHAR(50) NOT NULL,
    devoured BOOLEAN,
    PRIMARY KEY (id)
);